apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gdppm-data-pvc
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi